/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tech_startech_picktime_NDKUtils */

#ifndef _Included_tech_startech_picktime_NDKUtils
#define _Included_tech_startech_picktime_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tech_startech_picktime_NDKUtils
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_tech_startech_picktime_NDKUtils_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     tech_startech_picktime_NDKUtils
 * Method:    reverse
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_tech_startech_picktime_NDKUtils_reverse
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     tech_startech_picktime_NDKUtils
 * Method:    blur
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_tech_startech_picktime_NDKUtils_blur
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     tech_startech_picktime_NDKUtils
 * Method:    desColor
 * Signature: ([I[III)[I
 */
JNIEXPORT jintArray JNICALL Java_tech_startech_picktime_NDKUtils_desColor
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

/*
 * Class:     tech_startech_picktime_NDKUtils
 * Method:    sketch
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_tech_startech_picktime_NDKUtils_sketch
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
